spring:
  datasource:
  #   url: jdbc:postgresql://localhost:5532/transaction
  #   username: postgres
  #   password: postgres
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    contexts: schema-change
    liquibase-schema: loan_transaction
  jpa:
    open-in-view: false
    properties:
      jakarta:
        properties:
          validation:
            mode: none
  # Allow grace timeout period for 20 seconds
  lifecycle.timeout-per-shutdown-phase: 20s
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak-server/auth/realms/your-realm
logging:
  level:
    Root: INFO
    # Reduce the logging from the rsql-jpa library, which is otherwise too excessive:
    com.github.tennaito.rsql: ERROR
keycloak:
  enabled: false
javers:
  # Don't let Javers create its tables
  sqlSchemaManagementEnabled: false
  
# Wait for requests to finish before shutting down:
server.shutdown: graceful
dina:
  auditing.enabled: true
  apiPrefix: /api/v1

rabbitmq:
  queue: dina.search.queue
  username: guest
  password: guest
  host: ${RABBITMQ_HOSTNAME:localhost}
messaging:
  isProducer: false
